### ISSUE TITLE
[ERROR] Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by Armaldio** [SimplifyJobs/webpack-ext-reloader#54]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Manjaro
  - Browser: Brave Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
  - Library Version: 1.1.8

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**
Hello, 

I'm trying to use this plugin with a vue3 app.

<details>
  <summary>Here is the complete error message</summary>

```
$ vue-cli-service build --mode development --watch

⠙  Building for development...[ Starting the Hot Extension Reload Server... ]
✔  Building for development...
 ERROR  TypeError: Cannot read property 'tap' of undefined
TypeError: Cannot read property 'tap' of undefined
    at /home/armaldio/Documents/Projects/refined-c3/node_modules/webpack-ext-reloader/dist/webpack:/webpack-ext-reloader/src/webpack/CompilerEventsFacade.ts:22:34
    at SyncHook.eval (eval at create (/home/armaldio/Documents/Projects/refined-c3/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:33:1)
    at SyncHook.lazyCompileHook (/home/armaldio/Documents/Projects/refined-c3/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/home/armaldio/Documents/Projects/refined-c3/node_modules/webpack/lib/Compiler.js:631:26)
    at /home/armaldio/Documents/Projects/refined-c3/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/armaldio/Documents/Projects/refined-c3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/armaldio/Documents/Projects/refined-c3/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/armaldio/Documents/Projects/refined-c3/node_modules/webpack/lib/Compiler.js:662:28)
    at /home/armaldio/Documents/Projects/refined-c3/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/armaldio/Documents/Projects/refined-c3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/armaldio/Documents/Projects/refined-c3/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/home/armaldio/Documents/Projects/refined-c3/node_modules/webpack/lib/Watching.js:41:32)
    at /home/armaldio/Documents/Projects/refined-c3/node_modules/webpack/lib/Watching.js:33:9
    at Compiler.readRecords (/home/armaldio/Documents/Projects/refined-c3/node_modules/webpack/lib/Compiler.js:529:11)
    at new Watching (/home/armaldio/Documents/Projects/refined-c3/node_modules/webpack/lib/Watching.js:30:17)
    at Compiler.watch (/home/armaldio/Documents/Projects/refined-c3/node_modules/webpack/lib/Compiler.js:244:10)
```
</details>

<details>
  <summary>Here is my vue.config.js file</summary>

```js
/* eslint-disable @typescript-eslint/no-var-requires */

const ExtensionReloader = require('webpack-ext-reloader');
const path = require('path');

module.exports = {
  chainWebpack: (config) => {
    config.optimization.delete('splitChunks');
  },
  configureWebpack: {
    plugins: [
      new ExtensionReloader({
        // manifest: 'public/manifest.json',
        entries: {
          contentScript: [
            'quickswitch',
            'headway',
          ],
          background: ['background'],
        },
      }),
    ],
  },
  pages: {
    quickswitch: {
      entry: 'src/apps/quickswitch/main.ts',
    },
    headway: {
      entry: 'src/apps/headway/main.ts',
    },
    background: {
      entry: 'src/background.ts',
    },
  },
};
```
</details>

<details>
  <summary>And here is my folder tree</summary>

```
➜ tree -I 'node_modules'             
.
├── babel.config.js
├── package.json
├── public
│   ├── debug.js
│   ├── favicon.ico
│   ├── icons
│   │   ├── 128.png
│   │   ├── 16.png
│   │   ├── 19.png
│   │   ├── 38.png
│   │   ├── 48.png
│   │   └── 724.png
│   ├── index.html
│   ├── _locales
│   │   └── en
│   │       └── messages.json
│   ├── manifest.json
│   ├── messaging-install.js
│   └── messaging.js
├── README.md
├── shims-vue.d.ts
├── src
│   ├── apps
│   │   ├── headway
│   │   │   ├── App.vue
│   │   │   ├── assets
│   │   │   │   └── logo.png
│   │   │   ├── main.ts
│   │   │   ├── utils.ts
│   │   │   └── widget.js
│   │   ├── quickswitch
│   │   │   ├── App.vue
│   │   │   ├── assets
│   │   │   │   └── logo.png
│   │   │   ├── main.ts
│   │   │   └── utils.ts
│   │   └── utils.ts
│   ├── background.ts
│   └── tree
│       └── tree.ts
├── tsconfig.json
├── typings.d.ts
├── vue.config.js
└── yarn.lock
```
</details>

NOTE: internally ve-cli use webpack 4

Thanks !

**Comment by rushilsrivastava** [comment]
Hi, `webpack-ext-reloader` is meant for webpack 5 and above, and will not work with webpack 4. If you are looking for webpack 4 support, I would recommend checking out: [`webpack-extension-reloader`](https://www.npmjs.com/package/webpack-extension-reloader), which works with webpack 4.
